version: '2'

services:
  hayatkurtar.web.api:
    env_file: 
      - hayatkurtar.env
    container_name: hayatkurtar.web.api.container
    image: furkaandogan/hayatkurtar.web.api:0.1
#   build:
#      context: ./hayatKurtar.web.api
#      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - hayatkurtar.db
#      - hayatkurtar.notification.api


#  hayatkurtar.notification.api:
#    image: furkaandogan/pushnotification:0.1
#    ports:
#      - 8081:80
    

  hayatkurtar.db:
    container_name: hayatkurtar.mongodb.container
    image: mongo:3.4
#   ports:
#     - 27017:27017
    volumes:
      - /apps/hayatkurtar/data/mongodb/:/data/db
    
