version: '2'

services:
  hayatkurtar.web.api:
    env_file: 
      - hayatkurtar.env
    container_name: hayatkurtar.web.api.container
    image: furkaandogan/hayatkurtar.web.api:0.1
#   build:
#      context: ./hayatKurtar.web.api
#      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - hayatkurtar.db
#      - hayatkurtar.notification.api


  #hayatkurtar.notification.api:
  #  image: furkaandogan/pushnotification:0.1
  #  ports:
  #    - 8081:80
    

  hayatkurtar.db:
    env_file: 
      - hayatkurtar.env
    container_name: hayatkurtar.mongodb.container
    image: furkaandogan/mongodb:0.2
#    build:
#      context: ./hayatKurtar.db
#      dockerfile: Dockerfile
#   ports:
#     - 27017:27017
    volumes:
      - ./apps/hayatkurtar/data/mongodb/:/data/mongodb-data-files
      - ./apps/hayatkurtar/logs/mongodb/:/data/mongodb-log-files
    
